# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Gems
gems: [jekyll-paginate]

# Site settings
title: my_posts.sh
email: redacted@redacted.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
github_username: xb4dc0d3
theme: jekyll-theme-hacker
permalink: /:categories/:day/:month/:year/:title:output_ext
paginate: 5

# Build settings
markdown: kramdown
